import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { getFilingById, computeStatus } from '../utils/filings';
import { Document, Page, Text, View, StyleSheet, PDFDownloadLink, Font } from "@react-pdf/renderer";

// PDF Styles & Component
Font.register({
  family: 'Oswald',
  src: 'https://fonts.gstatic.com/s/oswald/v13/Y_TKV6o8WovbUd3m_X9aAA.ttf'
});

const styles = StyleSheet.create({
  page: { flexDirection: 'column', padding: 30, backgroundColor: '#FFFFFF' },
  section: { margin: 10, padding: 10, flexGrow: 1 },
  header: { fontSize: 24, marginBottom: 20, textAlign: 'center', fontFamily: 'Oswald' },
  subHeader: { fontSize: 18, borderBottom: '1px solid #000', marginBottom: 10, marginTop: 15 },
  row: { flexDirection: 'row', marginBottom: 5 },
  label: { fontSize: 12, fontWeight: 'bold', width: 120 },
  value: { fontSize: 12, flex: 1 },
  text: { fontSize: 11, lineHeight: 1.5, textAlign: 'justify' },
  disclaimer: { fontSize: 10, marginTop: 30, color: 'grey', textAlign: 'center' }
});

// Helper for filler text
const lorem = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";

const PatentPDFDocument = ({ filing }) => (
  <Document>
    {/* Page 1: Dossier Summary */}
    <Page size="A4" style={styles.page}>
      <View style={styles.section}>
        <Text style={styles.header}>Patent Application Dossier</Text>
        <Text style={{ textAlign: 'center', fontSize: 12, marginBottom: 20 }}>Ref: {filing.applicationNumber || "PENDING"}</Text>

        <Text style={styles.subHeader}>Bibliographic Data</Text>
        <View style={styles.row}><Text style={styles.label}>Title:</Text><Text style={styles.value}>{filing.title}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Applicant:</Text><Text style={styles.value}>{filing.applicantName}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Nationality:</Text><Text style={styles.value}>{filing.nationality}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Inventors:</Text><Text style={styles.value}>{filing.inventors ? filing.inventors.map(i => i.name || i).join(', ') : 'N/A'}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Filing Date:</Text><Text style={styles.value}>{filing.filingDate || "N/A"}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Status:</Text><Text style={styles.value}>{filing.status || computeStatus(filing)}</Text></View>

        <Text style={styles.subHeader}>Abstract Overview</Text>
        <Text style={styles.text}>{filing.abstractText || "No abstract provided."}</Text>

        <Text style={styles.subHeader}>Description Overview</Text>
        <Text style={{ fontSize: 11, fontWeight: 'bold', marginTop: 5 }}>Technical Field:</Text>
        <Text style={styles.text}>{filing.technicalField || "N/A"}</Text>

        <Text style={{ fontSize: 11, fontWeight: 'bold', marginTop: 5 }}>Problem Statement:</Text>
        <Text style={styles.text}>{filing.problemStatement || "N/A"}</Text>

        <Text style={{ fontSize: 11, fontWeight: 'bold', marginTop: 5 }}>Novelty Claims:</Text>
        <Text style={styles.text}>{filing.novelty || "N/A"}</Text>

        <Text style={styles.subHeader}>Document Index</Text>
        <Text style={{ fontSize: 10, color: 'grey', marginBottom: 5 }}>The following full-text documents are appended to this dossier:</Text>
        <View style={styles.row}><Text style={styles.label}>Appendix A:</Text><Text style={styles.value}>Specification ({filing.specificationFilePath || "Generated"})</Text></View>
        <View style={styles.row}><Text style={styles.label}>Appendix B:</Text><Text style={styles.value}>Claims ({filing.claimsFilePath || "Generated"})</Text></View>
        <View style={styles.row}><Text style={styles.label}>Appendix C:</Text><Text style={styles.value}>Drawings ({filing.drawingsFilePaths && filing.drawingsFilePaths.length > 0 ? `${filing.drawingsFilePaths.length} Sheet(s)` : "None"})</Text></View>

        <Text style={styles.disclaimer}>Generated by Global IPI Platform User Portal</Text>
      </View>
    </Page>

    {/* Page 2: Specification (Appendix A) */}
    <Page size="A4" style={styles.page}>
      <Text style={{ fontSize: 10, textAlign: 'right', marginBottom: 20, color: 'grey' }}>APPENDIX A: SPECIFICATION</Text>
      <Text style={styles.header}>SPECIFICATION</Text>
      <Text style={{ fontSize: 12, marginBottom: 10, textAlign: 'center', fontWeight: 'bold' }}>{filing.title}</Text>

      <Text style={styles.subHeader}>FIELD OF THE INVENTION</Text>
      <Text style={styles.text}>The present invention relates generally to {filing.technicalField || "the described field"}, and more specifically to systems and methods addressing {filing.problemStatement ? filing.problemStatement.substring(0, 50) + "..." : "complex technical challenges"}.</Text>

      <Text style={styles.subHeader}>BACKGROUND</Text>
      <Text style={styles.text}>{filing.problemStatement || "No background provided."}</Text>
      <Text style={{ ...styles.text, marginTop: 10 }}>{lorem}</Text>

      <Text style={styles.subHeader}>SUMMARY OF THE INVENTION</Text>
      <Text style={styles.text}>{filing.abstractText || "No summary provided."}</Text>

      <Text style={styles.subHeader}>DETAILED DESCRIPTION</Text>
      <Text style={styles.text}>In one embodiment, the invention provides {filing.novelty}.</Text>
      <Text style={{ ...styles.text, marginTop: 10 }}>Referring to the drawings, {lorem}</Text>
      <Text style={{ ...styles.text, marginTop: 10 }}>Furthermore, {lorem} {lorem}</Text>
    </Page>

    {/* Page 3: Claims (Appendix B) */}
    <Page size="A4" style={styles.page}>
      <Text style={{ fontSize: 10, textAlign: 'right', marginBottom: 20, color: 'grey' }}>APPENDIX B: CLAIMS</Text>
      <Text style={styles.header}>CLAIMS</Text>
      <Text style={{ fontSize: 12, marginBottom: 20 }}>What is claimed is:</Text>

      <View style={{ flexDirection: 'row', marginBottom: 10 }}>
        <Text style={{ width: 30, fontSize: 11 }}>1.</Text>
        <Text style={styles.text}>A system for {filing.title}, comprising:</Text>
      </View>
      <Text style={{ ...styles.text, marginLeft: 30, marginBottom: 10 }}>{filing.novelty || "a processor; and a memory storing instructions..."}.</Text>

      <View style={{ flexDirection: 'row', marginBottom: 10 }}>
        <Text style={{ width: 30, fontSize: 11 }}>2.</Text>
        <Text style={styles.text}>The system of claim 1, wherein said novelty comprises {filing.novelty ? filing.novelty.split(' ').slice(0, 5).join(' ') : "features"} configured to optimize performance.</Text>
      </View>

      <View style={{ flexDirection: 'row', marginBottom: 10 }}>
        <Text style={{ width: 30, fontSize: 11 }}>3.</Text>
        <Text style={styles.text}>A method for implementing {filing.title}, the method comprising steps corresponding to the system of claim 1.</Text>
      </View>
    </Page>

    {/* Page 4: Drawings (Appendix C) */}
    <Page size="A4" style={styles.page}>
      <Text style={{ fontSize: 10, textAlign: 'right', marginBottom: 20, color: 'grey' }}>APPENDIX C: DRAWINGS</Text>
      <Text style={styles.header}>DRAWINGS</Text>
      {filing.drawingsFilePaths && filing.drawingsFilePaths.length > 0 ? (
        filing.drawingsFilePaths.map((path, idx) => (
          <View key={idx} style={{ marginBottom: 30, alignItems: 'center', border: '1px dashed grey', padding: 50 }}>
            <Text style={{ fontSize: 14, fontWeight: 'bold', marginBottom: 10 }}>FIG. {idx + 1}</Text>
            <Text style={{ fontSize: 10, color: 'grey' }}>File: {path}</Text>
            <Text style={{ fontSize: 10, marginTop: 20, fontStyle: 'italic' }}>[Drawing Content Placeholder]</Text>
          </View>
        ))
      ) : (
        <Text style={{ textAlign: 'center', marginTop: 50, color: 'grey' }}>No drawings were attached to this application.</Text>
      )}
    </Page>

  </Document>
);

const RealTrackingTimeline = ({ filing }) => {
  const steps = [
    { label: 'Priority Date', date: filing.priorityDate, desc: 'Initial priority filing' },
    { label: 'Application Filed', date: filing.filingDate, desc: 'Patent application officially filed' },
    { label: 'Published', date: filing.publicationDate, desc: 'Patent published for public access' },
    { label: 'Patent Granted', date: filing.grantDate, desc: 'Patent legally granted' }
  ];

  return (
    <div className="relative border-l-2 border-white/20 ml-3 space-y-8 py-2">
      {steps.map((step, idx) => (
        <div key={idx} className="relative pl-6">
          <div className={`absolute -left-[9px] top-0 w-4 h-4 rounded-full border-2 border-white/30 ${step.date ? 'bg-green-500 shadow-[0_0_10px_rgba(34,197,94,0.6)]' : 'bg-blue-500'}`} />
          <div>
            <h4 className="text-sm font-semibold text-white">{step.label}</h4>
            <p className="text-xs text-white/50">{step.date || '—'}</p>
            <p className="text-xs text-white/40 mt-0.5">{step.desc}</p>
          </div>
        </div>
      ))}
    </div>
  );
};

const StandardTimeline = ({ filing }) => {
  const steps = ['Filed', 'Under Review', 'Approved', 'Granted', 'EXPIRED'];
  // We map backend status to timeline steps.
  // We can add "Pending Response" or others if needed, but let's stick to a main flow.

  // Statuses: FILED, Under Review, Under Examination, Pending Response, APPROVED, GRANTED, REJECTED, Withdrawn, EXPIRING SOON, EXPIRED
  const status = filing.status || 'FILED';

  let currentIndex = 0;
  if (status === 'Under Review' || status === 'Pending Response' || status === 'Under Examination') currentIndex = 1;
  else if (status === 'APPROVED') currentIndex = 2;
  else if (status === 'GRANTED') currentIndex = 3;
  else if (status === 'EXPIRED') currentIndex = 4;
  else if (status === 'REJECTED' || status === 'Withdrawn') currentIndex = -1; // Specific handling?

  return (
    <div className="space-y-4">
      {steps.map((s, i) => {
        let isActive = i <= currentIndex;
        let isCurrent = i === currentIndex;
        let dateValues = [filing.filingDate, null, null, filing.grantDate, filing.expiryDate];

        return (
          <div key={s} className="flex items-center gap-4">
            <div className={`w-3 h-3 rounded-full ${isActive ? (isCurrent ? 'bg-yellow-400' : 'bg-green-400') : 'bg-white/20'}`} />
            <div>
              <div className={`text-sm font-medium ${isActive ? 'text-white' : 'text-white/50'}`}>{s}</div>
              {dateValues[i] && <div className="text-xs text-white/50">{dateValues[i]}</div>}
            </div>
          </div>
        );
      })}
    </div>
  );
};

const FilingTimeline = ({ filing }) => {
  // Determine if this is a "real" tracked filing or a user submission
  const isTracked = filing.source === 'IP_SEARCH' || filing.priorityDate || filing.publicationDate;

  if (isTracked) return <RealTrackingTimeline filing={filing} />;
  return <StandardTimeline filing={filing} />;
};

const MyFilingDetail = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [filing, setFiling] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchFiling = async () => {
      try {
        setLoading(true);
        // Only fetch User Submitted Patent (Submission)
        const f = await getFilingById(parseInt(id));
        setFiling(f);
      } catch (error) {
        console.error('Failed to load filing:', error);
        setFiling(null);
      } finally {
        setLoading(false);
      }
    };
    if (id) fetchFiling();
  }, [id]);

  const handleDocClick = (docName) => {
    alert(`Demo Limitation: Actual file content for "${docName}" was not persisted to the server (only the filename was tracked). The 'Download Dossier' PDF lists these files as part of the official record.`);
  };

  if (loading) return <div className="min-h-screen bg-gradient-to-br from-[#2A1A4A] via-[#301B55] to-[#4B1F70] text-white p-6 flex justify-center items-center">Loading...</div>;
  if (!filing) return <div className="min-h-screen bg-gradient-to-br from-[#2A1A4A] via-[#301B55] to-[#4B1F70] text-white p-6 justify-center flex">Filing not found</div>;

  const status = computeStatus(filing);

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#2A1A4A] via-[#301B55] to-[#4B1F70] text-white p-6">
      <div className="max-w-6xl mx-auto space-y-6">
        {/* Header */}
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between bg-white/5 p-6 rounded-2xl border border-white/10 backdrop-blur-sm shadow-xl gap-4">
          <div>
            <div className="flex items-center gap-3">
              <button onClick={() => navigate('/my-filings')} className="text-white/60 hover:text-white transition-colors">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M19 12H5M12 19l-7-7 7-7" /></svg>
              </button>
              <h1 className="text-3xl font-bold tracking-tight">{filing.title}</h1>
            </div>
            <p className="text-white/60 mt-1 ml-9">App #: <span className="font-mono text-purple-200">{filing.applicationNumber || "PENDING"}</span> • {filing.jurisdiction} • Last Updated: {new Date(filing.updatedAt || Date.now()).toLocaleDateString()}</p>
          </div>
          <div className="flex items-center gap-3">
            <div className={`px-4 py-1.5 rounded-full text-xs font-bold tracking-wide uppercase ${status === 'GRANTED' ? 'bg-green-500/20 text-green-300 border border-green-500/30' : 'bg-blue-500/20 text-blue-300 border border-blue-500/30'}`}>{status}</div>
            <PDFDownloadLink document={<PatentPDFDocument filing={{ ...filing, status }} />} fileName={`Patent_${filing.applicationNumber || 'Draft'}.pdf`}>
              {({ loading }) => (
                <button className="flex items-center gap-2 bg-purple-600 hover:bg-purple-500 text-white px-5 py-2 rounded-lg transition-all font-medium shadow-lg hover:shadow-purple-500/25">
                  <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" /><polyline points="7 10 12 15 17 10" /><line x1="12" y1="15" x2="12" y2="3" /></svg>
                  {loading ? 'Generating...' : 'Download Dossier'}
                </button>
              )}
            </PDFDownloadLink>
          </div>
        </div>

        {/* ADMIN FEEDBACK BANNER */}
        {filing.adminFeedback && (
          <div className="bg-blue-500/10 border border-blue-500/30 rounded-xl p-4 flex gap-4">
            <div className="p-2 bg-blue-500/20 rounded-full h-fit">
              <svg className="w-6 h-6 text-blue-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
            <div>
              <h3 className="font-semibold text-blue-200">Latest Update from Examiner</h3>
              <p className="text-blue-100/80 mt-1">{filing.adminFeedback}</p>
            </div>
          </div>
        )}

        {/* Main Content Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

          {/* Left Column: Details */}
          <div className="lg:col-span-2 space-y-6">
            {/* Applicant & Inventors (New) */}
            <div className="bg-white/5 p-6 rounded-2xl border border-white/10 backdrop-blur-sm">
              <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#22d3ee" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2" /><circle cx="9" cy="7" r="4" /><path d="M23 21v-2a4 4 0 0 0-3-3.87" /><path d="M16 3.13a4 4 0 0 1 0 7.75" /></svg>
                Applicant & Inventors
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <label className="text-xs text-purple-300 uppercase font-bold tracking-wider mb-1 block">Applicant Name</label>
                  <p className="text-white font-medium text-lg">{filing.applicantName}</p>
                  <p className="text-white/60 text-sm mt-1">{filing.nationality}</p>
                </div>
                <div>
                  <label className="text-xs text-purple-300 uppercase font-bold tracking-wider mb-1 block">Inventors</label>
                  <div className="flex flex-wrap gap-2">
                    {filing.inventors && filing.inventors.length > 0 ? (
                      filing.inventors.map((inv, i) => (
                        <span key={i} className="inline-block bg-purple-500/20 text-purple-200 text-sm px-3 py-1 rounded-full border border-purple-500/30">
                          {inv.name || (typeof inv === 'string' ? inv : '')}
                        </span>
                      ))
                    ) : <span className="text-white/50">N/A</span>}
                  </div>
                </div>
              </div>
            </div>

            {/* Abstract */}
            <div className="bg-white/5 p-6 rounded-2xl border border-white/10 backdrop-blur-sm">
              <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#a78bfa" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" /><polyline points="14 2 14 8 20 8" /><line x1="16" y1="13" x2="8" y2="13" /><line x1="16" y1="17" x2="8" y2="17" /><polyline points="10 9 9 9 8 9" /></svg>
                Abstract
              </h3>
              <p className="text-white/80 leading-relaxed text-sm bg-black/20 p-4 rounded-xl border border-white/5">
                {filing.abstractText || "No abstract provided."}
              </p>
            </div>

            {/* Full Description */}
            <div className="bg-white/5 p-6 rounded-2xl border border-white/10 backdrop-blur-sm">
              <h3 className="text-lg font-semibold mb-4">Detailed Description</h3>

              <div className="space-y-6">
                <div>
                  <label className="text-xs text-purple-300 uppercase font-bold tracking-wider mb-2 block">Technical Field</label>
                  <p className="text-white/90 text-sm">{filing.technicalField || "N/A"}</p>
                </div>

                <div>
                  <label className="text-xs text-purple-300 uppercase font-bold tracking-wider mb-2 block">Problem Statement</label>
                  <p className="text-white/80 text-sm leading-relaxed">{filing.problemStatement || "N/A"}</p>
                </div>

                <div>
                  <label className="text-xs text-purple-300 uppercase font-bold tracking-wider mb-2 block">Novelty Claims & Invention</label>
                  <p className="text-white/80 text-sm leading-relaxed">{filing.novelty || "N/A"}</p>
                </div>
              </div>
            </div>
          </div>

          {/* Right Column: Timeline & Metadata */}
          <div className="space-y-6">
            {/* Timeline Card */}
            <div className="bg-white/5 p-6 rounded-2xl border border-white/10 backdrop-blur-sm">
              <h3 className="text-lg font-semibold mb-4">Application Timeline</h3>
              <FilingTimeline filing={filing} />
            </div>

            {/* Metadata Card */}
            <div className="bg-white/5 p-6 rounded-2xl border border-white/10 backdrop-blur-sm space-y-4 text-sm">
              <h3 className="text-lg font-semibold mb-2">Filing Metadata</h3>

              <div className="grid grid-cols-2 gap-y-4 pt-2 border-t border-white/5 mt-2">
                <div>
                  <div className="text-white/50 text-xs">Filing Date</div>
                  <div className="text-white font-medium">{filing.filingDate || "N/A"}</div>
                </div>
                <div>
                  <div className="text-white/50 text-xs">Applicant Type</div>
                  <div className="text-white font-medium">{filing.applicantType || "N/A"}</div>
                </div>
              </div>
            </div>

            {/* Documents Card */}
            <div className="bg-white/5 p-6 rounded-2xl border border-white/10 backdrop-blur-sm">
              <h3 className="text-lg font-semibold mb-4">Documents</h3>
              {(!filing.specificationFilePath && !filing.claimsFilePath && (!filing.drawingsFilePaths || filing.drawingsFilePaths.length === 0)) ? (
                <div className="text-white/50 text-sm italic">No documents recorded.</div>
              ) : (
                <ul className="space-y-2">
                  {filing.specificationFilePath && (
                    <li onClick={() => handleDocClick("Specification")} className="flex justify-between items-center p-3 bg-black/20 rounded-lg border border-white/5 hover:border-blue-400/50 cursor-pointer transition-colors group">
                      <div className="flex items-center gap-3">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-blue-400"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" /><polyline points="14 2 14 8 20 8" /><line x1="16" y1="13" x2="8" y2="13" /><line x1="16" y1="17" x2="8" y2="17" /><polyline points="10 9 9 9 8 9" /></svg>
                        <span className="text-sm group-hover:text-blue-300 transition-colors">Specification: <span className="text-white/60">{filing.specificationFilePath}</span></span>
                      </div>
                      <span className="text-xs text-white/40">Ref</span>
                    </li>
                  )}
                  {filing.claimsFilePath && (
                    <li onClick={() => handleDocClick("Claims")} className="flex justify-between items-center p-3 bg-black/20 rounded-lg border border-white/5 hover:border-blue-400/50 cursor-pointer transition-colors group">
                      <div className="flex items-center gap-3">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-blue-400"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" /><polyline points="14 2 14 8 20 8" /><line x1="16" y1="13" x2="8" y2="13" /><line x1="16" y1="17" x2="8" y2="17" /><polyline points="10 9 9 9 8 9" /></svg>
                        <span className="text-sm group-hover:text-blue-300 transition-colors">Claims: <span className="text-white/60">{filing.claimsFilePath}</span></span>
                      </div>
                      <span className="text-xs text-white/40">Ref</span>
                    </li>
                  )}
                  {filing.drawingsFilePaths && filing.drawingsFilePaths.length > 0 && (
                    <li onClick={() => handleDocClick("Drawings")} className="flex justify-between items-center p-3 bg-black/20 rounded-lg border border-white/5 hover:border-yellow-400/50 cursor-pointer transition-colors group">
                      <div className="flex items-center gap-3">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-yellow-400"><rect x="3" y="3" width="18" height="18" rx="2" ry="2" /><circle cx="8.5" cy="8.5" r="1.5" /><polyline points="21 15 16 10 5 21" /></svg>
                        <span className="text-sm group-hover:text-yellow-200 transition-colors">Drawings ({filing.drawingsFilePaths.length})</span>
                      </div>
                      <span className="text-xs text-white/40">Ref</span>
                    </li>
                  )}
                </ul>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default MyFilingDetail;
